name: CI - Windows
on: [pull_request, push]

jobs:
  build:
    name: 🚧Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      prog_name: mainui.exe

    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: '📥 Install dependencies'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-qt5-static
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-python
          mingw-w64-x86_64-boost

    - name: '🚧 Build curl'
      run: |
        cd curl
        cmake \
          -B build/mingw \
          -G "Ninja" \
          -DBUILD_SHARED_LIBS=OFF
        cmake --build build
        cd build/mingw
        cmake --install . --prefix=install
        cd ../..

    - name: '🚧 Build package'
      run: |
        cmake \
          -B build \
          -G "Ninja" \
          -DCMAKE_PREFIX_PATH=/mingw64/qt5-static \
          -DCURL_DIR=curl/build/mingw/install/lib/cmake/CURL
        cmake --build build
        mkdir build/dist
        cp build/${{env.prog_name}} build/dist
        python ldd-check/ldd-check.py -cp build/dist/${{env.prog_name}}

    - name: '🪕 Test package'
      run: |
        python server.py &
        cp config/config.txt build/dist/
        ./build/dist/${{env.prog_name}}
        python -m pytest .

    - name: '📤 upload package'
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/dist
